### ISSUE TITLE
Request for add AE2 Stuff

### ISSUE THREAD

**Issue by Diomendos** [Unhook/Celestial-Journey#12]
Hi,

I just want to ask if you can add AE2 Stuff by bdew, that would fit good in my opinion. As much as I like AE2, but the Inscriber and Growth mechanic is very frustrating to automate without this addon. 

Link: https://www.curseforge.com/minecraft/mc-mods/ae2-stuff
1.12.2 Version: https://www.curseforge.com/minecraft/mc-mods/ae2-stuff/files/2491032

Also would be nice if you could update the Questing mod, as the new menu is worst that it close all time. The newer version have a button to keep the side menu open. So would be great if you can update this also.

Rest locks really great and I'm looking to enjoy my journey :D

Thx.

Greetings Sebastian

**Comment by Ozzymud** [comment]
Just wanted to comment that the inscribers can be easily automated with EnderIO (https://imgur.com/t/applied_energistics_2/JLYSseN), the chest could be replaced with an interface. The whole setup can even be made with just AE2 parts and fully automated: https://imgur.com/a/uIwO7. 

As for the seeds, I'm pretty sure they can be grown in the TE Phytogenic Insolator. Add in some auxiliary reception coils to speed it up somewhat, it is slow but if you set it up to keep X of each on hand that is a non issue. You could again use entirely AE2 for automation as well, here are a couple of builds: https://imgur.com/a/t963A

**Comment by Unhook** [comment]
Better Questing was updated in a recent version. Won't add AE2 Stuff.
