### ISSUE TITLE
Divine RGP Armor

### ISSUE THREAD

**Issue by DerMart1** [Unhook/Celestial-Journey#14]
Somehow my Bedrockium Armor doesnt provide the fire and blast resistance after a while.
Once i had poison from the cave spider and then fire protection wanished. But it does seam to have another or more different reasons. Would be nice if you could fix this issue because otherwise these armours are unnecessary. Greetings

**Comment by Unhook** [comment]
That is something you should report to the DivineRPG devs -https://github.com/NicosaurusRex99/DivineRPG/issues - not to me.
