### ISSUE TITLE
To be or not to be (just see) :D

### ISSUE THREAD

**Issue by GiaruDK** [Unhook/Celestial-Journey#15]
Hi,

I want to offer a couple of mods that need to be added, among them there are those that are simply necessary for any assembly, and some situational ones that can also be added, but it will be necessary to balance each of them correctly :3

For your convenience, I will divide them into categories and importance.

The mods that must be added I will mark with three ***

The mods that it is desirable to add for the acquisition of great emotions from passing modpack I note two **

And the most relatively unnecessary I note one *

So let's get started :D

0.Modular Machinery

- Modular Diversity (but you need to downgrade MM to 1.10) (https://www.curseforge.com/minecraft/mc-mods/modular-diversity) we need more modular machine :3 ***

1.Botania Addons

- ManaVisualizer (https://www.curseforge.com/minecraft/mc-mods/manavisualizer) just convenient tool ***
- Botania Needs These Things! (https://www.curseforge.com/minecraft/mc-mods/botania-needs-these-things) mana chargers ***
- ExtraBotany (https://www.curseforge.com/minecraft/mc-mods/extrabotany) adds 3 tier gaia and more cool content **
- More Flowers (https://www.curseforge.com/minecraft/mc-mods/more-flowers/screenshots) new generation flora **

2.Thaumcraft Addons

- Thaumic Periphery (https://www.curseforge.com/minecraft/mc-mods/thaumic-periphery) adds more cool item and bubles **
- Thaumic Additions: Reconstructed (https://www.curseforge.com/minecraft/mc-mods/thaumic-additions) just amazing mod, adds more cool content in thaumcraft **

3.TIC Addons

- Pewter (https://www.curseforge.com/minecraft/mc-mods/pewter) more new modificators, supports more mods ***
- Yoyos (https://www.curseforge.com/minecraft/mc-mods/yoyos) supports Botania too :3 ***
- Tweakers Construct (https://www.curseforge.com/minecraft/mc-mods/tweakers-construct) Tic + Content tweaker = new cool recipe ***
- Tinker I/O (https://www.curseforge.com/minecraft/mc-mods/tinker-i-o) adds convenient things for TIC ***
- Tinkering with Blood Magic (https://www.curseforge.com/minecraft/mc-mods/tinkering-with-blood-magic) just convenient mod **

4.AE2

- PackagedAvaritia (https://www.curseforge.com/minecraft/mc-mods/packagedavaritia) addon to PackagedAuto ***
- AE2 Network Visualiser (https://www.curseforge.com/minecraft/mc-mods/ae2-network-visualiser) ***
- Applied Integrations (https://www.curseforge.com/minecraft/mc-mods/applied-integrations) need more integrations :D **

5.Other

- Compact Machines (https://www.curseforge.com/minecraft/mc-mods/compact-machines) for lovers of beautiful and cospact houses **
- ME Capability Adapter (https://www.curseforge.com/minecraft/mc-mods/capability-adapter) needed for the past mod **
- /dank/null (https://www.curseforge.com/minecraft/mc-mods/dank-null) obligatory thing always ***
- Solar Flux Reborn (https://www.curseforge.com/minecraft/mc-mods/solar-flux-reborn) very cool solar panels, supports Thaumcraft, Avaritia and Draconic Evolution <3 **
- Exchangers (https://www.curseforge.com/minecraft/mc-mods/exchangers) just exchanger blocks ***
- Hooked (https://www.curseforge.com/minecraft/mc-mods/hooked) best mod to move 0_0 ***
- Flux Networks (https://www.curseforge.com/minecraft/mc-mods/flux-networks) best energy I\O **
- ArchitectureCraft (https://www.curseforge.com/minecraft/mc-mods/architecturecraft-tridev) builders will appreciate ) ***

Thank you for paying attention to my post, I hope for your early reply.

Let's continue to promote this wonderful assembly, I hope you will be helped by the list of mods that I selected for you.

Yours truly, GiaruDK <3

Thx.

**Comment by Unhook** [comment]
Blood Agricraft is already in the pack. Other mods listed probably won't get added.

**Comment by GiaruDK** [comment]
Of course I don’t make you add it all. But I would like that there would be progress in content, and not just 1 in 1 port. 

Frankly, I'm just trying to help and nothing more, I and many other players are interested in the development of the modpack, a variety of ways. The generation of energy here is not personally thought out at all (I want the world of rf tools 5tier and even with upgrades it needs 60k rf per tick, and generators do a maximum of 25k rf, the reactor can be accelerated by 200k, and if the world is not 1 but 10 pieces, create lag generator from syngas generators mixed with reactors is not cool). You didn’t think about builders at all; many people in the chat were for adding the builder’s sticks and the architect’s workshop. 

In all additions of thaumcraft to version 1.7.10, you did not find adequate replacements for them. About the mandatory akashic book and morph wrech do not even need to talk.

And the last one. Think about it yourself if you chose the path to continue the legacy of the legendary modpack, and this does not mean that you should do everything 1 in 1, it would be quite appropriate to supplement it with new content, and do it purely to improve your gaming experience. I think even AtricosHU itself would say about the same thing, because quite a lot of time has passed, a lot of things have been changed, abandoned, a lot of new interesting mods have been added (in the sense of mods that in their idea would suit the assembly). In general, only you think, I hope you make the right decisions, and we will all see a new dawn of the legend) <3

Yours truly, GiaruDK <3

**Comment by Unhook** [comment]
Just because you want a certain mod added doesn't mean it should be added. You can add building/decoration related mods such as Better Builder's Wand and Chinese Workshop perfectly fine on your own. We've looked at the various Thaumcraft addons and do not feel like they would add anything significant to the pack. That being said, this pack is first and foremost meant to be a port of Divine Journey. We have added some new content (e.g. in the form of Modular Machinery) and have plans to add more new content in the future. However, the aim is not to just add new mods for the sake of adding mods.
Anyways, serious and well-thought-out suggestions are always considered - so please keep doing so.

**Comment by Unhook** [comment]
That also means that I'm not necessarily not going to add any of the mods you listed to the pack in the future, I just don't have any plans to do so right now.

**Comment by GiaruDK** [comment]
Yes, I agree, I also talked about plans for the future, you will add a little to future updates and test)) And yes, I will probably clean the list from unnecessary mods, there are a couple of mods that are suitable for modpack.

Yours truly, GiaruDK <3

**Comment by Unhook** [comment]
Added Akashic Tome, Better Builder's Wands and Morph-o-Tool in version 1.0.7

**Comment by jellonek** [comment]
I see that some of players (e.g. https://www.youtube.com/user/Cr4zYSpY ) are adding dank null and I think that I understand that, as excavating near bedrock using rupee shickaxe or EFL can be painful to maintain with a row of dev nulls and the variety of useful ores...
For me it was one of more irritating parts of beginning of the pack when while mining I had to dump and dump again every few seconds big part of inventory into a backpack (autopickup option of satchels help a bit later but still dank null is more user friendly...).

**Comment by jellonek** [comment]
Btw. you are featuring To Asgaard let's play while he is again playing a modified version of this pack, so some people can be confused when they will see betweenlands in his play series while it's not in the pack...

**Comment by Unhook** [comment]
> Btw. you are featuring To Asgaard let's play while he is again playing a modified version of this pack, so some people can be confused when they will see betweenlands in his play series while it's not in the pack...

Eh, ok? I don't see the problem here.

**Comment by Ozzymud** [comment]
> Eh, ok? I don't see the problem here.  

My son was watching the let's play from the curseforge page after seeing me play the pack. He was all hyped to play it as well because it had Betweenlands (just from watching ToAsgaard). He was confused when I told him it was not in the pack. The curseforge page is the advertisement for the pack. So let's plays that you feature there should be ones where people are playing the actual pack and not a largely modified one... Betweenlands is a huge mod, it aint like he changed a preference or something.

**Comment by Unhook** [comment]
> > Eh, ok? I don't see the problem here.
> 
> My son was watching the let's play from the curseforge page after seeing me play the pack. He was all hyped to play it as well because it had Betweenlands (just from watching ToAsgaard). He was confused when I told him it was not in the pack. The curseforge page is the advertisement for the pack. So let's plays that you feature there should be ones where people are playing the actual pack and not a largely modified one... Betweenlands is a huge mod, it aint like he changed a preference or something.

Still don't see the problem. He literally mentions several times that they are not included in the pack and that he added them himself (see latest video: it's even in the title and is the first thing he mentions).
