### ISSUE TITLE
Unstable Ingot crafting

### ISSUE THREAD

**Issue by DerMart1** [Unhook/Celestial-Journey#16]
Sorry if I'm dumb but if i try to craft an unstable ingot with an activated Division Sign in an vanilla crafting table it wont craft   EDIT : it may be an issue with the "vanilla" crafting table being from Fast Workbench 
I dont know if this is a bug or if i'm just stupid but would be nice if you help me.
Thanks in advance ^^.

**Comment by Unhook** [comment]
You're right. Will remove the mod in the next version

**Comment by Unhook** [comment]
Fixed in version 1.1.1
