### ISSUE TITLE
Can't make alchemical brass

### ISSUE THREAD

**Issue by happaes** [Unhook/Celestial-Journey#20]
I can not make alchemical brass. I have completed the research but there is no recipe for it in the Thaumonomicon. There is a crucible recipe present in JEI (1 Energetic Alloy Ingot + 5 instrumentum) but when I try this, no brass ingot is created. I tried different items that give instrumentum.

![image](https://user-images.githubusercontent.com/63115635/78382255-d4b05b00-75d6-11ea-8a81-2b179ee8b459.png)

**Comment by Unhook** [comment]
Fixed in version 1.1.5
