### ISSUE TITLE
Thaumcraft infusion issue

### ISSUE THREAD

**Issue by Felonster** [Unhook/Celestial-Journey#23]
Hey,
I have a problem with the reaserch in the thaumonomicon called 'infusion', i crafted 2 runic matrix in order to complete the task, but it doesnt seem to complete. I crafted first by auto crafting, and second one by manualy completing crafting with wand. Both didnt work

**Comment by Unhook** [comment]
You need to complete its quest to get the research

**Comment by Felonster** [comment]
i havent played with thaumcraft much so i dont know how  is it called, but i meant this
![celestial](https://user-images.githubusercontent.com/63251332/78591940-82747180-7844-11ea-87e3-99f46bf8f30a.png)
it dont want to complete even after i crafted matrix

**Comment by Unhook** [comment]
Yes, you need to complete its quest in the quest book.

**Comment by Felonster** [comment]
![image](https://user-images.githubusercontent.com/63251332/78603025-b60cc700-7857-11ea-8d67-f7e9c6a5e8be.png)
This one?

**Comment by Unhook** [comment]
Completing the one with the runic matrix icon gives you the research, yes.

**Comment by Felonster** [comment]
Well, thats the problem. First message i wrote was after i completed quest in the questbook
