### ISSUE TITLE
Enabling the Enhanced alloy smelter

### ISSUE THREAD

**Issue by kamyflouge** [Unhook/Celestial-Journey#26]
I know it’d have to be really late game and expensive but even after adding the same alloy smeltry recipe to multiple alloy smeltries with octople capacitors it’s still slow.i could do something about every tedious challenge , except this one

**Comment by Felonster** [comment]
You can set an alloy smelter to make alloy passively the time and leave it for some time running. It should fix your alloy problem

**Comment by Unhook** [comment]
No.
