### ISSUE TITLE
Players Crashing when entering dimensions from DivineRPG mobs

### ISSUE THREAD

**Issue by coffeeordeath** [Unhook/Celestial-Journey#29]
The server we run has had multiple issues with people getting crashes upon loading into the End, Eden, and Wildwood. This is an example of one that just happened that to myself, though i do have numerous others. 

https://gist.github.com/coffeeordeath/78b68f5c87df2fbdad94ee0c9cff7e39

**Comment by Unhook** [comment]
https://github.com/NicosaurusRex99/DivineRPG/issues/119
