### ISSUE TITLE
Missing recipe - Lead- and Tin-nuggets to Ingot

### ISSUE THREAD

**Issue by tjsd** [Unhook/Celestial-Journey#31]
Hello!
I recently made the agricraft plants for Lead and Tin, but you forgot to have a nugget to ingot and reverse recipe. So I cant turn them into ingots in a drawer.

Looking at the Lead Ingot and Tin Ingot recipes, they use thaumcraft nuggets, but agricraft makes thermalfoundation nuggets.

**Comment by Unhook** [comment]
Fixed in version 2.0.6
