### ISSUE TITLE
cant fill the scribing tools with ink

### ISSUE THREAD

**Issue by KitanaShaw** [Unhook/Celestial-Journey#32]
when trying to refill the scribing tools with ink using ink sac or other black dyes it wont let me craft it
![javaw_2020-04-28_16-41-21](https://user-images.githubusercontent.com/36748695/80494589-7ecd9980-896f-11ea-948b-b8756a794c5f.png)
![javaw_2020-04-28_16-41-33](https://user-images.githubusercontent.com/36748695/80494596-7ffec680-896f-11ea-825c-293d83b75d30.png)
![javaw_2020-04-28_16-42-06](https://user-images.githubusercontent.com/36748695/80494597-80975d00-896f-11ea-8f9c-eea89b9aa1fd.png)
![javaw_2020-04-28_16-42-32](https://user-images.githubusercontent.com/36748695/80494599-80975d00-896f-11ea-89c0-ab7d133d0bd7.png)

i'm currently running 2.0.2

i will be updating later today and check if i can craft the recipe

**Comment by KitanaShaw** [comment]
still cant be crafted in 2.0.7

**Comment by Bizuex** [comment]
I had the same issue. If you enchant (enderIO enchanter) it with mending you can fill it on a xp tank.
