### ISSUE TITLE
Unable to craft the special sticks from Natura's nether trees

### ISSUE THREAD

**Issue by jumpkain** [Unhook/Celestial-Journey#39]
Version: 2.1.3
Mode: Single player survival

Issue:

I went to craft some Ghostwood Fence to put around my home and noticed that it required Ghostwood Sticks rather than vanilla ones. However, attempting to craft such sticks will result in vanilla ones instead (even if you humor JEI and put the planks in the exact spots listed in the crafting grid). This means that players are currently unable to craft anything requiring Ghostwood sticks. Looking further in JEI, Natura's overworld trees such as Amaranth and Willow have a recipe that involves placing the sticks diagonally - this recipe works properly. All of the trees found in the Nether (Ghostwood, Darkwood, Fusewood, Bloodwood) copy the vertical vanilla recipe. Though I've only personally tested Ghostwood, I assume the other 3 fail to craft as well.

Proposed fix:

Adjusting the recipes for the 4 wood types mentioned above to require the planks to be placed diagonally to avoid conflicting with the vanilla recipe would probably be the cleanest fix.

**Comment by Unhook** [comment]
Fixed in version 2.1.4
