### ISSUE TITLE
Some recipes are different than the original (within reason)

### ISSUE THREAD

**Issue by ariosos** [Unhook/Celestial-Journey#41]
I was just looking at the Basic Machine Chassis, and it is the "vanilla" Ender IO recipe (not sure if it was intentional or not, but EnderIO was gated behind TE). The original has the Thermal Expansion Machine Frame and capacitor.

Suggestion - Give the Basic Machine Chassis the original 1.7.10 recipe, and for the Industrial Machine Chassic, replace the organic black dye with grains of infinity.

Basic Cards also used Signalum Ingots instead of gold in 1.7.10, and gave 2 cards.

**Comment by Unhook** [comment]
All intended.
