### ISSUE TITLE
Into the Twilight

### ISSUE THREAD

**Issue by Ozzymud** [Unhook/Celestial-Journey#6]
v: 1.0.2
Quest "Into the Twilight" does not detect. Stading in the TF and even manual detect doesn't trigger it, just finished killing the naga.  

Edit: Tried re-entering, nothing - https://i.imgur.com/58ClA9q.png

**Comment by Unhook** [comment]
Odd. This worked fine before - I'll change it to a checkbox quest in the next version as it just doesn't detect it.

**Comment by Unhook** [comment]
Fixed in version 1.0.4 - thank you for reporting all these bugs.

**Comment by Ozzymud** [comment]
No worries, happy to help :)
