### ISSUE TITLE
Consider tooltip and or quest for Eye of Ender

### ISSUE THREAD

**Issue by Ozzymud** [Unhook/Celestial-Journey#7]
Not sure if it is a quest somewhere or something I missed but after dying to endermen more times then I cared, I was gonna disable them teleporting me. While looking in the configs for that I stumbled across the bit about holding an eye in inventory to stop them from teleporting me. 

I get it's expert, but this mod is not a popular one so I doubt many would know about the mechanic, at a bare minimum consider adding a tooltip, possibly even adding a quest to get an ender pearl/eye of ender to let folks know about the whole keep an eye in inventory.

**Comment by Unhook** [comment]
Added a tooltip to the eye of ender in version 1.0.5
