### ISSUE TITLE
Basic Capacitor Bank recipe NBT crafting problem

### ISSUE THREAD

**Issue by Ozzymud** [Unhook/Celestial-Journey#9]
Cannot craft the Basic Capacitor bank after "using" the Energy Cell (Basic). The recipe calls for one with 7 NBT tags, mine has 8. It was briefly charged via a Flux Capacitor in my inventory. Turning off the Capacitor or storing it before crafting the basic cell solves the issue. So the recipe just needs altering so this doesn't happen at all.

**Comment by Unhook** [comment]
Fixed in version 1.0.6
